source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'Segment-AurycSDK-iOS_Example' do
  
  pod 'Analytics', '~> 3.0'
  pod 'Segment-AurycSDK-iOS', :path => '../'
#  pod 'Segment-CleverTap'
  
  pod 'AurycSDK', :path => '/Users/alcides.zelaya/Documents/Auryc/auryc-ios-sdk'

end
